### ISSUE TITLE
How to set checkbox values checked using formController.getModel().setValue() method

### ISSUE THREAD

**Issue by Feroz-Istar** [dkharrat/NexusDialog#29]
How to set checkbox values checked using formController.getModel().setValue() method

**Comment by dkharrat** [comment]
You would set the value to a `Set` containing the items selected. If you're `CheckBoxController` is created with  the flag `useItemsAsValues` set to false, the items in the `Set` must be the 0-based index of the selected items. Otherwise, the items in the set must each be a `String` representing the item to select.
