### ISSUE TITLE
How can we change the style / theme of individual controls?

### ISSUE THREAD

**Issue by elprl** [dkharrat/NexusDialog#6]
Other than adding a global style to every EditText in your app, how can we change the look of individual EditTexts in a form?

**Comment by elprl** [comment]
For example, how can we change the font colour of the section headers?

**Comment by dkharrat** [comment]
For changing the style of the section headers, the easiest way is to override the .xml that defines the style of the element (`form_section.xml`). This can be done by adding an xml file with the same name to your application. Android will then use your xml layout instead of the one defined by NexusDialog. Just be sure to define elements having the same `id` that NexusDialog expects.

As form elements, they all use `form_labeled_element.xml` as a container layout, which you can also override similar to above. However, the actual field (e.g. EditText, etc.) is programmatically created, so it can't be easily overridden unless you create a subclass. We could perhaps define an .xml style to support customizations. What's your use case specifically?

**Comment by elprl** [comment]
Cheers for the response. I will try the xml override. 

My use case was just to match the look & feel to the brand of the app.

**Comment by elprl** [comment]
You may want to add your above response to the help readme.
